### ISSUE TITLE
Use commandPrefix for callback instead of proc names

### ISSUE THREAD

**Issue by ssteidl** [flightaware/tclrmq#2]
Currently procedure names are required for all callbacks instead of commandPrefixes.  This can be frustrating because there is no way to add any context to the callbacks.  Also apply cannot be used for callbacks.  

I believe the only thing that will be required to use commandPrefixes is to add a {*} before invoking each callback.

**Comment by wasichu** [comment]
I have a decent idea of what you're requesting, but, for full clarification, can you please provide an example of what the code would look like if your requested feature was implemented?  I am trying to get a more complete sense of the use case here.

**Comment by ssteidl** [comment]
Sure.  I implemented the feature for onConnected and basicConsume at https://github.com/ssteidl/tclrmq/commit/a1b8e1caeb4d2311d963a6b6f2104fb2eb3f46c7

The hello world tutorial shows how/why it is useful to do it that way.  It's the tcl way to allow context in callbacks, like passing a void* in a c callback or using std::bind in c++

**Comment by wasichu** [comment]
Feature has been added in [release v1.3.3](https://github.com/flightaware/tclrmq/releases/tag/v1.3.3).

Thanks for the suggestion!
